# For more information: https://laravel.com/docs/sail
version: '3.4'
services:
    farmyard:
        build:
            context: ./.docker
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - farmyard
        depends_on:
            - mysql
            - redis
    mysql:
        image: 'mariadb:10.3'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'farmyardmysql:/var/lib/mysql'
            - './.docker/mysql:/etc/mysql/conf.d'
        networks:
            - farmyard
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'farmyardredis:/data'
        networks:
            - farmyard
    # memcached:
    #     image: 'memcached:alpine'
    #     ports:
    #         - '11211:11211'
    #     networks:
    #         - ordersninja
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - farmyard
networks:
    farmyard:
        driver: bridge
volumes:
    farmyardmysql:
        driver: local
    farmyardredis:
        driver: local
